### ISSUE TITLE
Latest version of datagen broke the driver

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_driver#46]
This is what happens when trying to run on SF1 generated by datagen 0.2:

    INFO  com.ldbc.driver.Client  Loaded DB: hpl.alp2.titan.drivers.interactive.TitanFTMDb
    INFO  com.ldbc.driver.Client  Scanning workload streams to calculate their limits...
    ERROR com.ldbc.driver.Client  Client terminated unexpectedly
    com.ldbc.driver.ClientException: Error loading workload class: com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbInteractiveWorkload
        at com.ldbc.driver.Client$ExecuteWorkloadMode.init(Client.java:251)
        at com.ldbc.driver.Client.<init>(Client.java:137)
        at com.ldbc.driver.Client.main(Client.java:49)
    Caused by: java.lang.NumberFormatException: Invalid digit character -3 '�' where the original char was '-'
        at com.ldbc.driver.csv.Extractors.digit(Extractors.java:660)
        at com.ldbc.driver.csv.Extractors.extractLong(Extractors.java:652)
        at com.ldbc.driver.csv.Extractors.access$000(Extractors.java:63)
        at com.ldbc.driver.csv.Extractors$LongExtractor.extract(Extractors.java:242)
        at com.ldbc.driver.csv.BufferedCharSeeker.extract(BufferedCharSeeker.java:164)
        at com.ldbc.driver.workloads.ldbc.snb.interactive.WriteEventStreamReaderCharSeeker$EventDecoderAddPerson.decodeEvent(WriteEventStreamReaderCharSeeker.java:110)
        at com.ldbc.driver.workloads.ldbc.snb.interactive.WriteEventStreamReaderCharSeeker$EventDecoderAddPerson.decodeEvent(WriteEventStreamReaderCharSeeker.java:71)
        at com.ldbc.driver.generator.CsvEventStreamReaderTimedTypedCharSeeker.getNextEvent(CsvEventStreamReaderTimedTypedCharSeeker.java:81)
        at com.ldbc.driver.generator.CsvEventStreamReaderTimedTypedCharSeeker.next(CsvEventStreamReaderTimedTypedCharSeeker.java:42)
        at com.ldbc.driver.workloads.ldbc.snb.interactive.WriteEventStreamReaderCharSeeker.next(WriteEventStreamReaderCharSeeker.java:63)
        at com.ldbc.driver.workloads.ldbc.snb.interactive.WriteEventStreamReaderCharSeeker.next(WriteEventStreamReaderCharSeeker.java:16)
        at com.google.common.collect.Iterators$PeekingImpl.peek(Iterators.java:1162)
        at com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbInteractiveWorkload.getStreams(LdbcSnbInteractiveWorkload.java:291)
        at com.ldbc.driver.Workload.streams(Workload.java:45)
        at com.ldbc.driver.WorkloadStreams.createNewWorkloadWithLimitedWorkloadStreams(WorkloadStreams.java:175)
        at com.ldbc.driver.WorkloadStreams.createNewWorkloadWithLimitedWorkloadStreams(WorkloadStreams.java:165)
        at com.ldbc.driver.Client$ExecuteWorkloadMode.init(Client.java:245)
        ... 2 more

**Comment by tomersagi** [comment]
This seems to be resolved now.
