### ISSUE TITLE
Strange validation error - expected Query 6 got Query 5?

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_driver#51]
Hi ,
I'm receiving a strange error on ShortQuery6.
This is the error:

```
Operation:        LdbcShortQuery6MessageForum{messageId=42949710942}
    Expected Result:  LdbcShortQuery6MessageForumResult{forumId=42949675368, forumTitle='Group for Rembrandt in Quetta', moderatorId=3298534883614, moderatorFirstName='Mirza Kalich', moderatorLastName='Ahmed'}
    Actual Result  :  LdbcShortQuery5MessageCreatorResult{personId=2199023256420, firstName='Li', lastName='Li'}
```

This is my code for short query 6:

```Java
public class LdbcShortQuery6Handler implements OperationHandler<LdbcShortQuery6MessageForum,TitanFTMDb.BasicDbConnectionState> {
    final static Logger logger = LoggerFactory.getLogger(LdbcShortQuery6Handler.class);

    @Override
    public void executeOperation(final LdbcShortQuery6MessageForum operation,TitanFTMDb.BasicDbConnectionState dbConnectionState,ResultReporter resultReporter) {
        long mid = operation.messageId();
        TitanFTMDb.BasicClient client = dbConnectionState.client();
        Vertex m;
        try {
            logger.debug("Short Query 6 called on message id: {}", mid);
            m = client.getVertex(mid, "Comment");
            if (m==null)
                m = client.getVertex(mid, "Post");

            GremlinPipeline<Vertex,Vertex> gp = new GremlinPipeline<>(m);
            Iterator<Row> qResult = gp.in("containerOf").as("forum").out("hasModerator").as("person").select();
            if (!qResult.hasNext())
            {
                logger.error("Unexpected empty set");
                return;
            }

            Row r = qResult.next();
                Vertex forum = (Vertex)r.getColumn("forum");
                Vertex person = (Vertex)r.getColumn("person");

                LdbcShortQuery6MessageForumResult res = new LdbcShortQuery6MessageForumResult(
                        client.getVLocalId((Long)forum.getId()),
                        (String)forum.getProperty("title"),
                        client.getVLocalId((Long)person.getId()),
                        (String) person.getProperty("firstName"),(String) person.getProperty("lastName"));
                resultReporter.report(1, res, operation);
        } catch (SchemaViolationException e) {
        e.printStackTrace();
        resultReporter.report(-1, null, operation);
    }

    }
```

This doesn't make sense. 
Ideas?
Thanks,
Tomer

**Comment by tomersagi** [comment]
After updating the driver I get the following error:

```
Client  Client terminated unexpectedly
com.ldbc.driver.ClientException: Encountered error while writing to file
File: C:\Users\sagit\workspace\ldbc_benchmarkFTM\titanFTM_driver\target\test-classes\workloads\validation_params-failed-actual.json
	at com.ldbc.driver.Client$ValidateDatabaseMode.execute(Client.java:650)
	at com.ldbc.driver.Client.start(Client.java:141)
	at com.ldbc.driver.Client.main(Client.java:50)
	at hpl.alp2.titan.test.DriverTest.testDriver(DriverTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.ClassCastException: com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcShortQuery5MessageCreatorResult cannot be cast to com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcShortQuery6MessageForumResult
	at com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcShortQuery6MessageForum.serializeResult(LdbcShortQuery6MessageForum.java:52)
	at com.ldbc.driver.validation.DbValidationResult.operationAndResultAsJsonMapString(DbValidationResult.java:110)
	at com.ldbc.driver.validation.DbValidationResult.actualResultsForFailedOperationsAsJsonString(DbValidationResult.java:70)
	at com.ldbc.driver.Client$ValidateDatabaseMode.execute(Client.java:646)
	... 26 more
```
