### ISSUE TITLE
Missing parameter

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_driver#56]
Hi guys,
I’m running the LDBC benchmark again and ran into an issue:

```com.ldbc.driver.ClientException: Error loading workload class: com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbInteractiveWorkload
        at com.ldbc.driver.client.ExecuteWorkloadMode.doInit(ExecuteWorkloadMode.java:245)
        at com.ldbc.driver.client.ExecuteWorkloadMode.startExecutionAndAwaitCompletion(ExecuteWorkloadMode.java:156)
        at com.ldbc.driver.Client.main(Client.java:50)
Caused by: com.ldbc.driver.WorkloadException: Configuration parameter missing: ldbc.snb.interactive.short_read_dissipation
        at com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbInteractiveWorkload.onInit(LdbcSnbInteractiveWorkload.java:258)
        at com.ldbc.driver.Workload.init(Workload.java:30)
        at com.ldbc.driver.WorkloadStreams.createNewWorkloadWithOffsetAndLimitedWorkloadStreams(WorkloadStreams.java:260)
        at com.ldbc.driver.WorkloadStreams.createNewWorkloadWithOffsetAndLimitedWorkloadStreams(WorkloadStreams.java:233)
        at com.ldbc.driver.client.ExecuteWorkloadMode.doInit(ExecuteWorkloadMode.java:231)```

I took the ldbc_driver.properties file from here: https://github.com/ldbc/ldbc_driver/tree/master/configuration 
And the workload properties file from here: https://github.com/ldbc/ldbc_driver/tree/master/configuration/ldbc/snb/interactive 

None have this parameter.
Please explain

**Comment by tomersagi** [comment]
My bad, I spliced the config files and missed a line
