### ISSUE TITLE
Empty result crashes driver

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_driver#57]
Hi,
I'm running SF3 of the interactive workload and the driver crashed. I think the problem stems from a null result. Short query 6 requires you to return the forum and moderator of the forum for a given message. The invocation was done on a message ID that is not contained in any forum:

```
grep '549764685440' *.csv
comment_0_0.csv:549764685440|2012-10-18T13:17:30.279+0000|111.223.40.47|Internet Explorer|cool|4|
comment_hasCreator_person_0_0.csv:549764685440|10995116300880|
comment_isLocatedIn_place_0_0.csv:549764685440|103|
comment_replyOf_comment_0_0.csv:549764685440|549764685439|
```

Therefore, my handler returned a null instead of an LdbcShortQuery6MessageForumResult. 

This is what happened:

```
14:12:02.355 [ThreadPoolOperationExecutor-id(1441883512286)-thread(0)] DEBUG h.a.t.d.i.LdbcShortQuery6Handler - Short Query 6 called on message id: 549764685440
14:12:02.358 [ThreadPoolOperationExecutor-id(1441883512286)-thread(0)] ERROR h.a.t.d.i.LdbcShortQuery6Handler - Unexpected empty set
14:12:02.359 [ThreadPoolOperationExecutor-id(1441883512286)-thread(0)] DEBUG h.a.t.d.i.LdbcQuery10Handler - Query 10 called on Person id: 16492674430835 with month number 8
14:12:02.365 [ThreadPoolOperationExecutor-id(1441883512286)-thread(0)] DEBUG h.a.t.d.i.LdbcShortQuery1Handler - Short Query 1 called on person id: 5497558164391
14:12:02.368 [ThreadPoolOperationExecutor-id(1441883512286)-thread(0)] DEBUG h.a.t.d.i.LdbcShortQuery2Handler - Short Query 2 called on person id: 10995116286781
Shutting down status thread...
ExecuteWorkloadMode  Shutting down workload...
Client  Client terminated unexpectedly
com.ldbc.driver.ClientException: Error running workload
        at com.ldbc.driver.client.ExecuteWorkloadMode.doExecute(ExecuteWorkloadMode.java:425)
        at com.ldbc.driver.client.ExecuteWorkloadMode.startExecutionAndAwaitCompletion(ExecuteWorkloadMode.java:157)
        at com.ldbc.driver.Client.main(Client.java:50)
Caused by: com.ldbc.driver.ClientException: Error running workload

- Start Error Log -
        SOURCE: ThreadPoolExecutorWithAfterExecute (Thread: ID=32, Name=ThreadPoolOperationExecutor-id(1441883512286)-thread(0), Priority=5)
        ERROR:  Error retrieving handler
java.lang.ClassCastException: com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcShortQuery5MessageCreatorResult cannot be cast to com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcShortQuery6MessageForumResult
        at com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbShortReadGenerator$ResultBufferReplenishFun.replenish(LdbcSnbShortReadGenerator.java:510)
        at com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbShortReadGenerator.nextOperation(LdbcSnbShortReadGenerator.java:371)
        at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor$ThreadPoolExecutorWithAfterExecute.afterExecute(ThreadPoolOperationExecutor.java:221)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

        SOURCE: WorkloadRunnerThread (Thread: ID=24, Name=Thread-2, Priority=5)
        ERROR:  Encountered error while shutting down
com.ldbc.driver.runtime.executor.OperationExecutorException: Error encountered while trying to shutdown
        at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor.shutdown(ThreadPoolOperationExecutor.java:131)
        at com.ldbc.driver.runtime.WorkloadRunner$WorkloadRunnerThread.shutdownEverything(WorkloadRunner.java:509)
        at com.ldbc.driver.runtime.WorkloadRunner$WorkloadRunnerThread.run(WorkloadRunner.java:418)
Caused by: com.ldbc.driver.runtime.executor.OperationExecutorException: ThreadPoolOperationExecutor shutdown before all handlers could complete
895 handlers were queued for execution but not yet started
1 handlers were mid-execution
        at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor.shutdown(ThreadPoolOperationExecutor.java:125)
        ... 2 more

- End Error Log -

```

I think it was caused by the empty result set of Short Query 6, but I'm not sure. 
1. What should the handler return with a short query that has nothing to return. 
2. Can the driver overcome this case more gracefully?
Thanks
Tomer

**Comment by alexaverbuch** [comment]
Hi @tomersagi , 
Thanks for reporting this. The short answer is this:
(1) the driver should indeed report this in a better way. I've made a note in my TODO list
(2) returning null is invalid. operation handlers should *always* return an instance of the appropriate result class. besides the ugly error message, this is not a driver fault
(3) you should never get a null result for a short read. I can't be certain but am 99% sure this null is due to an error in your connector

**Comment by tomersagi** [comment]
Thanks for the rapid response. 
About (2) ok, about (3) as you can see in the grep I did on the csv's generated by the data generator, this message has no forum (no containerOf edge). Therefore I have nothing to return.

**Comment by alexaverbuch** [comment]
@tomersagi,
(4) What version of the driver are you using? What exact commit?
(2)
```
Given a Message (Post or Comment), retrieve the Forum that contains it and the Person that
moderates that forum. Since comments are not directly contained in forums, for comments, return the forum containing the original post in the thread which the comment is replying to
```

**Comment by tomersagi** [comment]
(4) 0.3-snapshot da8eda2e21dd342daafc31f375017630dff3cd4f
(2) You're right, thanks

**Comment by alexaverbuch** [comment]
thanks Tomer
