### ISSUE TITLE
Driver crashes on short query 6 (expecting list?)

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_driver#58]
Driver crashed, from the stack trace below looks like something is expecting a list. But the query definition and signature call for a single result to be returned. 
```
Shutting down status thread...
ExecuteWorkloadMode  Shutting down workload...
Client  Client terminated unexpectedly
com.ldbc.driver.ClientException: Error running workload
        at com.ldbc.driver.client.ExecuteWorkloadMode.doExecute(ExecuteWorkloadMode.java:425)
        at com.ldbc.driver.client.ExecuteWorkloadMode.startExecutionAndAwaitCompletion(ExecuteWorkloadMode.java:157)
        at com.ldbc.driver.Client.main(Client.java:50)
Caused by: com.ldbc.driver.ClientException: Error running workload

- Start Error Log -
        SOURCE: ThreadPoolExecutorWithAfterExecute (Thread: ID=32, Name=ThreadPoolOperationExecutor-id(1442494762702)-thread(0), Priority=5)
        ERROR:  Error retrieving handler
java.lang.ClassCastException: com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcShortQuery6MessageForumResult cannot be cast to java.util.List
        at com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbShortReadGenerator$ResultBufferReplenishFun.replenish(LdbcSnbShortReadGenerator.java:515)
        at com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbShortReadGenerator.nextOperation(LdbcSnbShortReadGenerator.java:371)
        at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor$ThreadPoolExecutorWithAfterExecute.afterExecute(ThreadPoolOperationExecutor.java:221)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

        SOURCE: WorkloadRunnerThread (Thread: ID=24, Name=Thread-2, Priority=5)
        ERROR:  Encountered error while shutting down
com.ldbc.driver.runtime.executor.OperationExecutorException: Error encountered while trying to shutdown
        at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor.shutdown(ThreadPoolOperationExecutor.java:131)
        at com.ldbc.driver.runtime.WorkloadRunner$WorkloadRunnerThread.shutdownEverything(WorkloadRunner.java:509)
        at com.ldbc.driver.runtime.WorkloadRunner$WorkloadRunnerThread.run(WorkloadRunner.java:418)
Caused by: com.ldbc.driver.runtime.executor.OperationExecutorException: ThreadPoolOperationExecutor shutdown before all handlers could complete
895 handlers were queued for execution but not yet started
1 handlers were mid-execution
        at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor.shutdown(ThreadPoolOperationExecutor.java:125)
        ... 2 more

- End Error Log -

        at com.ldbc.driver.client.ExecuteWorkloadMode.doExecute(ExecuteWorkloadMode.java:420)
        ... 2 more

java.lang.IllegalStateException: Operation cannot be executed because the enclosing transaction is closed
        at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.verifyOpen(StandardTitanTx.java:283)
        at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getVertex(StandardTitanTx.java:368)
        at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:40)
        at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:24)
        at com.thinkaurelius.titan.graphdb.internal.AbstractElement.isNew(AbstractElement.java:112)
        at com.thinkaurelius.titan.graphdb.query.vertex.BasicVertexCentricQueryBuilder.executeImplicitKeyQuery(BasicVertexCentricQueryBuilder.java:162)
        at com.thinkaurelius.titan.graphdb.query.vertex.VertexCentricQueryBuilder.properties(VertexCentricQueryBuilder.java:84)
        at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.getProperty(AbstractVertex.java:136)
        at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.getProperty(AbstractVertex.java:152)
        at com.tinkerpop.blueprints.util.wrappers.id.IdElement.getProperty(IdElement.java:33)
        at hpl.alp2.titan.drivers.interactive.LdbcShortQuery2Handler.executeOperation(LdbcShortQuery2Handler.java:46)
        at hpl.alp2.titan.drivers.interactive.LdbcShortQuery2Handler.executeOperation(LdbcShortQuery2Handler.java:25)
        at com.ldbc.driver.OperationHandlerRunnableContext.run(OperationHandlerRunnableContext.java:121)
        at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor$ThreadPoolExecutorWithAfterExecute.afterExecute(ThreadPoolOperationExecutor.java:219)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by alexaverbuch** [comment]
what commit of driver are you using?
after your last issue I made some changes to how 'null' returns are handled.
I suspect this error is caused by your connector returning null.

**Comment by tomersagi** [comment]
Using the latest commit, same issue occurs. I'll try stepping through ShortQuery 6.

**Comment by alexaverbuch** [comment]
@tomersagi do you mind sharing the stack trace again please?

**Comment by tomersagi** [comment]
sure http://pastebin.com/1LZf6JGs

**Comment by alexaverbuch** [comment]
@tomersagi what commit are you at?

**Comment by tomersagi** [comment]
820d9d5559884e03bd1902d9bc1c2530bf22f5ce

**Comment by alexaverbuch** [comment]
please show me the output of `git log`

**Comment by alexaverbuch** [comment]
the error printout you showed contains this
```
java.lang.ClassCastException: com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcShortQuery6MessageForumResult cannot be cast to java.util.List
        at com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbShortReadGenerator$ResultBufferReplenishFun.replenish(LdbcSnbShortReadGenerator.java:515)
        at com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbShortReadGenerator.nextOperation(LdbcSnbShortReadGenerator.java:371)
        at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor$ThreadPoolExecutorWithAfterExecute.afterExecute(ThreadPoolOperationExecutor.java:221)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
when I look at, for example,
`com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbShortReadGenerator$ResultBufferReplenishFun.replenish(LdbcSnbShortReadGenerator.java:515)` that doesn't align with the commit you mention because `LdbcSnbShortReadGenerator.java:515` contains this:
```
this.personIdBuffer = personIdBuffer;
```
which could not throw that exception. see:
https://github.com/ldbc/ldbc_driver/blob/master/src/main/java/com/ldbc/driver/workloads/ldbc/snb/interactive/LdbcSnbShortReadGenerator.java#L515

**Comment by tomersagi** [comment]
Maybe it wasn't installed properly, I'll try cleaning and installing

~/livegraph/source/ldbc_driver:master$ git pull
Already up-to-date.
~/livegraph/source/ldbc_driver:master$ git log
commit 820d9d5559884e03bd1902d9bc1c2530bf22f5ce
Author: Alex Averbuch <alex.averbuch@gmail.com>
Date:   Wed Sep 16 18:06:12 2015 +0200

    add files() to ResultsDirectory

commit f23c1ce01d95c567c77c07032188bfed1d6312ae
Author: Alex Averbuch <alex.averbuch@gmail.com>
Date:   Wed Sep 16 15:05:16 2015 +0200

    integrate results log validator into client and get tolerances from workload implementation

commit d4dc3f9fabe6537696960b0738f0587b43b4bb1d
Author: Alex Averbuch <alex.averbuch@gmail.com>
Date:   Wed Sep 16 13:09:14 2015 +0200

    add results log validation classes and integrate them into driver (still to figure out how to do workload-specific tolerances)

commit f4646a83b29a2885263f9a09b1270bc14730af12
Author: Alex Averbuch <alex.averbuch@gmail.com>
Date:   Sat Sep 12 12:22:09 2015 +0200

    remove boolean variable from ConcurrentErrorReporter impl
    move workload validation classes to test directory

commit 305e433925d479f2b89706ca252eccb8ce568d4c
Author: Alex Averbuch <alex.averbuch@gmail.com>
Date:   Sat Sep 12 12:05:33 2015 +0200

    update pom

commit 38ddf94fb18686b40a0809c792582ac5e1e284a3
Merge: 688ed19 20832dd
Author: Alex Averbuch <alex.averbuch@gmail.com>
Date:   Sat Sep 12 12:01:31 2015 +0200

    Merge branch 'dev-bi' into dev

commit 20832dd001c5d5f75b70286e410b8dc3c642ca8d
Author: Alex Averbuch <alex.averbuch@gmail.com>
Date:   Sat Sep 12 12:00:25 2015 +0200

**Comment by alexaverbuch** [comment]
yeah your git is up to date, maybe `rm -rf ~/.m2/repository/com/ldbc` and then try rebuilding?

**Comment by tomersagi** [comment]
ok, now the classes are correctly loaded from the latest ldbc version, I had to add throws statements to all handlers...

Here is the new stack trace:

http://pastebin.com/gBb0rD1k

**Comment by alexaverbuch** [comment]
yeah that's what I was warning you about when I sent this Skype message

```
when you update the driver again you will notice that ResultsReporter throws a DbException so your handlers will not compile. just add "throws DbException" to your handlers executeOperation() methods and all will be will (that method throws that exception already) -- I'm adding this to handle your "null result" in a nicer way
```

**Comment by alexaverbuch** [comment]
BTW, any idea why the "Error Log" gets printed 3 times for you?
I don't remember seeing that issue before, so it's either a newly introduced bug or something to do with your execution environment

**Comment by tomersagi** [comment]
No idea

**Comment by alexaverbuch** [comment]
@tomersagi can you confirm that you're returning null?

**Comment by alexaverbuch** [comment]
@tomersagi would you mind pushing your code to github, at the commit that threw this exception?
without that code it's a little hard to track this down, there are a few things that I'm now understanding here

**Comment by tomersagi** [comment]
pushed: https://github.com/ldbc/ldbc_snb_implementations/tree/master/interactive/titan

**Comment by tomersagi** [comment]
hmmm, I think that in ShortQuery 5 I'm not returning anything if no message creator was found. That means resultReporter is never invoked. I'll try and add a default empty invocation.

**Comment by tomersagi** [comment]
ok, That isn't the problem, although it's a good idea regardless. 
It seems that line 661 of the LdbcSnbShortReadGenerator is throwing the error since its trying to cast an ldbcShortQuery5Result to a list of LdbcShortQuery7Result. The operation is indeed LdbcShortQueryMessageReplies, but the result is of type ldbcShortQuery5MessageCreatorResult. 
I checked the handler for short query 7 and it returns a list of Short Query 7 results so that's not the problem.

**Comment by alexaverbuch** [comment]
@tomersagi from a quick look at your short query 5 handler I don't see the problem there. however, that type casting error is almost always indicative of a query handler that is not returning a result, or is returning a null result, so I'm still suspect that this is the cause. I'm going to add more checks to the driver tonight and push tomorrow, hopefully they will help to debug your issue.

BTW, here:
https://github.com/ldbc/ldbc_snb_implementations/blob/master/interactive/titan/titanFTM_driver/src/main/java/hpl/alp2/titan/drivers/interactive/LdbcShortQuery5Handler.java#L41
you should not do this (instead you should just re-throw the exception):
```
} catch (SchemaViolationException e) {
        e.printStackTrace();
        resultReporter.report(-1, null, operation);
}
```

**Comment by alexaverbuch** [comment]
@tomersagi I pushed the code early
https://github.com/ldbc/ldbc_driver/commit/9d3348c22508e92b8725ba7260c8a16fe4daef3a

if you use the latest commit (as above) and then send me the stack trace I think/**hope** the situation will be more clear

**Comment by tomersagi** [comment]
Remove all the exception handling codes from the query handlers? This negates your previous directive to add catch-all exception clauses to all query handlers. Are you sure?

**Comment by tomersagi** [comment]
ok, your latest commit fixed the issue.

**Comment by alexaverbuch** [comment]
The only thing it changed was how errors are reported.
It could not have removed an error, only presented it in a "better" way.
What was the new error message?

**Comment by tomersagi** [comment]
No error message at all

**Comment by alexaverbuch** [comment]
@tomersagi did you change your handler code?
there is no way that I can see my changes removing the bug you were seeing, that's why I would really appreciate as much information as possible here. 
you are the only person to see this error, which is why I suspect it was your implementation code. HOWEVER, if this was a driver bug I'd like to dig further into it.

BTW, regarding you other question

> Remove all the exception handling codes from the query handlers? This negates your previous directive to add catch-all exception clauses to all query handlers. Are you sure?

It was never necessary to catch all exceptions. `DbException` could always be thrown, and in the case that a query legitimately crashes throwing a `DbException` is currently the recommended thing for a connector to do. 
`ResultReporter.reportError(String, Exception)` could be an alternative in future, but at present nothing like that is supported

**Comment by tomersagi** [comment]
I changed my handler code to make it return an empty result instead of a null result, then I reran the driver before applying your latest commits and still got the error. Afterwards I a[[lied the latest changes to the driver and then re-ran and had no error message.
